/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_a111_ndk2_MyNdk */

#ifndef _Included_com_example_a111_ndk2_MyNdk
#define _Included_com_example_a111_ndk2_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_a111_ndk2_MyNdk
 * Method:    getFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_a111_ndk2_MyNdk_getFromNDK
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
